### ISSUE TITLE
[Issue]: broken rocm_jaxlib wheels

### ISSUE THREAD

**Issue by ksebaz** [ROCm/rocm-install-on-linux#233]
### Problem Description

The jaxlib wheel for version v0.4.30 (from https://github.com/ROCm/jax/releases) depend on glibc 2.31 but according to its label as 'manylinux2014' should only depend on glibc 2.17 (see https://github.com/pypa/manylinux).

### Operating System

irrelevant

### CPU

irrelevant

### GPU

AMD Radeon VII

### ROCm Version

ROCm 6.1.0

### Steps to Reproduce

wget python3 -m pip install https://github.com/ROCm/jax/releases/download/rocm-jaxlib-v0.4.30/jaxlib-0.4.30+rocm611-cp39-cp39-manylinux2014_x86_64.whl
auditwheel show jaxlib-0.4.30+rocm611-cp39-cp39-manylinux2014_x86_64.whl

**Comment by ksebaz** [comment]
Sorry copy-paste-error in the reproducer. Should be
```
wget https://github.com/ROCm/jax/releases/download/rocm-jaxlib-v0.4.30/jaxlib-0.4.30+rocm611-cp39-cp39-manylinux2014_x86_64.whl
auditwheel show jaxlib-0.4.30+rocm611-cp39-cp39-manylinux2014_x86_64.whl
```

**Comment by mrodden** [comment]
This is unfortunately a known issue. I am currently working on creating actual manylinux builds for the wheels that we publish for ROCm. The new wheels will be manylinux_2_28 (glibc 2.28 or greater), which hopefully will work for your use case. manylinux2014 is out of support at the end of the month I believe.

**Comment by ksebaz** [comment]
Ah sorry, I was not aware but I see it now from the links in the PR. Thanks for working on it!

**Comment by yhuiYH** [comment]
Looks like this was fixed in the upstream PR.  Closing this ticket.  Please re-open, if required.
