### ISSUE TITLE
Installing multiple ROCm versions[Documentation]: 

### ISSUE THREAD

**Issue by acaleechurn** [ROCm/rocm-install-on-linux#257]
### Description of errors

The multiple install documentation points to incorrect repos. The correct repo is 6.2 and not 6.2.0 as mentioned, which causes the install to fail. This can be confirmed by looking at the single version installation from https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/ubuntu.html where the repos are properly labelled.

for ver in **6.2.0** 6.1.2; do
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/$ver/ubuntu noble main" \
    | sudo tee /etc/apt/sources.list.d/amdgpu.list
done
sudo apt update

for ver in **6.2.0** 6.1.2; do
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/$ver noble main" \
    | sudo tee --append /etc/apt/sources.list.d/rocm.list
done
echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' \
    | sudo tee /etc/apt/preferences.d/rocm-pin-600
sudo apt update

**Comment by yhuiYH** [comment]
Sorry for the delay, and thanks for pointing this out.  https://github.com/ROCm/rocm-install-on-linux/pull/279 was merged to address this issue.

The docs have been updated where the folder path on repo.radeon.com are now "6.2". 
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/multi-version-install.html

Please close this issue once you confirm.

**Comment by yhuiYH** [comment]
Closing this ticket.  Please re-open, if required.
