### ISSUE TITLE
[Documentation]: GitHub URL in Offline Installer build from source instructions needs to be updated

### ISSUE THREAD

**Issue by AMD-melliott** [ROCm/rocm-install-on-linux#259]
### Description of errors

- GitHub URL in the Offline Installer build from source instructions (https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.2.0/install/rocm-offline-installer.html#building) needs to be changed from `git@github.com:ROCm/rocm-install-on-linux.git` to `https://github.com/ROCm/rocm-install-on-linux` for `git clone` to work without authentication
- The instructions in step 3 should be changed from `cd src/offline-install` to `cd rocm-install-on-linux/src/offline-installer`

I have a PR ready to submit with the proposed changes.

**Comment by yhuiYH** [comment]
The PR has been merged.  Closing this issue.  Please re-open, if required.
