### ISSUE TITLE
[Issue]: Experiencing Application Crashes when using ROCm 6.2 + Ubuntu 24.04

### ISSUE THREAD

**Issue by AC-amd** [ROCm/rocm-install-on-linux#262]
### Problem Description

```NAME="Ubuntu"
VERSION="24.04 LTS (Noble Numbat)"
CPU:
model name      : AMD Ryzen Threadripper PRO 7995WX 96-Cores
GPU:
  Name:                    AMD Ryzen Threadripper PRO 7995WX 96-Cores
  Marketing Name:          AMD Ryzen Threadripper PRO 7995WX 96-Cores
  Name:                    gfx1100
  Marketing Name:          AMD Radeon PRO W7900 Dual Slot
  Name:                    amdgcn-amd-amdhsa--gfx1100
  ```
I was previously on Ubuntu 22.04 + ROCm 6.1.2 and everything was fine. No problems whatsoever. 

I then updated to Ubuntu 24.04 + ROCm 6.2 (Latest) and now I'm experiencing the following:
- Applications won't Load/Crashes (Terminal and Settings won't even open)
- Once the systems goes to sleep mode, won't wake back up. Have to do a full reboot

Once I uninstall ROCm 6.2 and reboot, everything works just fine. No issues. I tried this with 3 different systems with the same hardwares. All experience the same issues. 
  

      
      
      

### Operating System

Ubuntu 24.04

### CPU

AMD Ryzen Threadripper PRO 7995WX 96-Cores

### GPU

AMD Radeon Pro W7900

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

1. Install Ubuntu 24.04
2. Install ROCm 6.2
3. Reboot
Apps will then either crash or wont open. Terminal and setting wont open.

Then
1. Uninstall ROCm 6.2
2. Reboot
Back to normal, apps load just fine, no issues

### Additional Information

[dmesg.txt](https://github.com/user-attachments/files/16567517/dmesg.txt)

**Comment by harkgill-amd** [comment]
Hi @Boi-KS, after installing ROCm 6.2, could you please run the following commands and provide the corresponding output/log.
```
sudo apt install mesa-utils
AMD_DEBUG=info glxinfo > glxinfo.log
```

**Comment by Nathan903** [comment]
im on ubuntu 22.04, same issue here.
Running `sudo apt install mesa-utils; AMD_DEBUG=info glxinfo > glxinfo.log` gives `Error: unable to open display:0`

**Comment by harkgill-amd** [comment]
@Nathan903, can you try to update your Mesa drivers by running the following.
```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update
sudo apt upgrade
```
After rebooting, do you still see the same issues?
