### ISSUE TITLE
[Issue]: Experiencing Application Crashes when using ROCm 6.2 + Ubuntu 22.04

### ISSUE THREAD

**Issue by Nathan903** [ROCm/rocm-install-on-linux#280]
### Problem Description

I ran the script in _Quick start installation guide_ 
```
sudo apt update
sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
sudo usermod -a -G render,video $LOGNAME # Add the current user to the render and video groups
wget https://repo.radeon.com/amdgpu-install/6.2/ubuntu/jammy/amdgpu-install_6.2.60200-1_all.deb
sudo apt install ./amdgpu-install_6.2.60200-1_all.deb
sudo apt update
sudo apt install amdgpu-dkms rocm
```
about 5 to 10 seconds after every reboot, the operating system freezes. Mouse is frozen, terminal does not open on ctrl+alt+t. 

I have replicated this issue on a freshly installed ubuntu system. 

Running `sudo apt install mesa-utils; AMD_DEBUG=info glxinfo > glxinfo.log` gives `Error: unable to open display:0`

I work in the Markham office if anyone would like to debug in person

### Operating System

Ubuntu 22.04.01

### CPU

AMD Ryzen 9 5950X

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

1. Install fresh 22.04 ubuntu by usb
2. run script
```
sudo apt update
sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
sudo usermod -a -G render,video $LOGNAME # Add the current user to the render and video groups
wget https://repo.radeon.com/amdgpu-install/6.2/ubuntu/jammy/amdgpu-install_6.2.60200-1_all.deb
sudo apt install ./amdgpu-install_6.2.60200-1_all.deb
sudo apt update
sudo apt install amdgpu-dkms rocm
```
3. reboot 
4. wait up to 30 seconds.

**Comment by Nathan903** [comment]
I tried the package manager installation method https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/ubuntu.html. While it does not freeze the screen all the time, it cause the system to freeze when I launch unreal engine (5.4.3). The log message it freezes on is "Initializing SDL"

I haven't tested any other software, so am not sure whether other softwares will also freeze

**Comment by harkgill-amd** [comment]
Hi @Nathan903, could you please ping me on teams and we can debug this together.

**Comment by AC-amd** [comment]
@harkgill-amd ill just ping you on teams as well then
