### ISSUE TITLE
[Issue]: rocm install fail with unmet  dependencies

### ISSUE THREAD

**Issue by bussyjd** [ROCm/rocm-install-on-linux#323]
### Problem Description

```
OS:
NAME="Ubuntu"
VERSION="24.04.1 LTS (Noble Numbat)"
CPU: 
model name	: AMD Ryzen 9 5950X 16-Core Processor
```

```
sudo apt install rocm
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsystemd-dev : Depends: libsystemd0 (= 255.4-1ubuntu8) but 255.4-1ubuntu8.4 is to be installed
 libzstd-dev : Depends: libzstd1 (= 1.5.5+dfsg2-2build1) but 1.5.5+dfsg2-2build1.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Operating System

Ubuntu 24.04.1 LTS

### CPU

AMD Ryzen 9 5950X

### GPU

AMD Radeon RX 7900 XT

### ROCm Version

ROCm 6.2.0

### Steps to Reproduce

upgrade LTS to ubuntu 24
Follow https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/ubuntu.html steps

### Additional Information

Similar issue (other entity)
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/native-install/ubuntu.html

**Comment by harkgill-amd** [comment]
Hi @bussyjd, looks like there's a version mismatch with `libsystemd-dev` and `libzstd-dev` . Could you please remove the existing ROCm dependencies with
```
sudo amdgpu-install --uninstall --rocmrelease=all
sudo apt purge amdgpu-install
sudo apt autoremove
```
and then reinstall with
```
wget https://repo.radeon.com/amdgpu-install/6.2.2/ubuntu/noble/amdgpu-install_6.2.60202-1_all.deb
sudo apt install ./amdgpu-install_6.2.60202-1_all.deb
sudo apt update
sudo amdgpu-install --usecase=rocm
```
This will reset the `amdgpu` and `rocm` repositories while also removing any previously installed packages.

**Comment by harkgill-amd** [comment]
Closing this issue out due to lack of response. If you're still encountering issues with the ROCm installation, feel free to leave a comment and I'll reopen this ticket.

**Comment by harkgill-amd** [comment]
Closing this issue out due to lack of response. If you're still encountering issues with the ROCm install, feel free to leave a comment and I'll reopen this ticket.
