### ISSUE TITLE
[Feature]: Can pytorch run in a host machine? Not in a docker machine

### ISSUE THREAD

**Issue by FlintWangacc** [ROCm/rocm-install-on-linux#331]
### Suggestion Description

Can pytorch not run in a preinstalled docker machine

### Operating System

ubuntu

### GPU

rtx7900xtx

**Comment by harkgill-amd** [comment]
Hi @FlintWangacc, you can run PyTorch+ROCm on your host machine by following the instructions for a baremetal installation at [Using a Wheels Package](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/3rd-party/pytorch-install.html#using-a-wheels-package) (Option 3).
