### ISSUE TITLE
[Documentation]: Running ROCm Docker containers

### ISSUE THREAD

**Issue by peterstrazovec** [ROCm/rocm-install-on-linux#338]
### Description of errors

[Docker compose sample code](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html) has a typo, it contains /dev/fdk instead of /dev/kfd

### Attach any links, screenshots, or additional evidence you think will be helpful.

<img width="342" alt="image" src="https://github.com/user-attachments/assets/9b696039-6eb3-4c67-ab72-b38ad74dde78">

**Comment by danielsu-amd** [comment]
Hi @peterstrazovec, I came across the same typo just yesterday and wrote a fix for it: https://github.com/ROCm/rocm-install-on-linux/pull/339. If you can confirm this resolves the error, please close this issue.

**Comment by yhuiYH** [comment]
Thanks you guys for pointing out the typo.  As @danielsu-amd mentioned, it should be fixed now, thanks to his PR: https://github.com/ROCm/rocm-install-on-linux/pull/339.  Closing this issue now, but please re-open, if necessary.
