### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by ekeever1** [ROCm/rocm-install-on-linux#350]
### Problem Description

Attempting to install rocm6.2.4 packages currently fails with package checksum error for rocm-smi-lib, and apparently rocm-core and potentially more. This was originally encountered with a large yum install that pulls in a full install but can be reproduced with just the smi-lib line below.

### Operating System

RHEL 8.10

### CPU

AMD MI300a

### GPU

AMD MI300a

### ROCm Version

ROCm 6.2.3

### ROCm Component

amdsmi

### Steps to Reproduce

1. Enable 6.2.4 repository in yum.repos.d,
`[rocm]
name=ROCm 6.2.4 repository
baseurl=https://repo.radeon.com/rocm/el8/6.2.4/main
enabled=1
gpgcheck=1
priority=50
gpgkey=file:///etc/amdgpu-install/rocm.gpg.key`
2. Enter a small part of the grand yum install command,
`yum install rocm-smi-lib6.2.4`
3. Receive checksum error,
```
[MIRROR] amd-smi-lib6.2.4-24.6.3.60204-139.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: fae4e8a96fedac18a76db081ba4de5419e84972351735348a4740d84ad2de6e3(sha256)  Expected: 010bca76a13c04e2e0a31369a5307bf7aa6b620ccd7e07f971cb47560ec6e545(sha256)
[MIRROR] amd-smi-lib6.2.4-24.6.3.60204-139.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: fae4e8a96fedac18a76db081ba4de5419e84972351735348a4740d84ad2de6e3(sha256)  Expected: 010bca76a13c04e2e0a31369a5307bf7aa6b620ccd7e07f971cb47560ec6e545(sha256)
[MIRROR] amd-smi-lib6.2.4-24.6.3.60204-139.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: fae4e8a96fedac18a76db081ba4de5419e84972351735348a4740d84ad2de6e3(sha256)  Expected: 010bca76a13c04e2e0a31369a5307bf7aa6b620ccd7e07f971cb47560ec6e545(sha256)
[MIRROR] amd-smi-lib6.2.4-24.6.3.60204-139.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: fae4e8a96fedac18a76db081ba4de5419e84972351735348a4740d84ad2de6e3(sha256)  Expected: 010bca76a13c04e2e0a31369a5307bf7aa6b620ccd7e07f971cb47560ec6e545(sha256)
[FAILED] amd-smi-lib6.2.4-24.6.3.60204-139.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(2-3/85): composablekernel-devel6.2.4-1.1.0.60204-139.el8.x86_6  0% [                                                              ] 5.5 MB/s | 5.1 MB     07:24 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: Error downloading packages:
  amd-smi-lib6.2.4-24.6.3.60204-139.el8.x86_64: Cannot download, all mirrors were already tried without success
```

**Comment by ppanchad-amd** [comment]
Hi @ekeever1. Thanks for reporting the issue. Internal ticket has been created to assist with the investigation. Thanks!

**Comment by tcgu-amd** [comment]
Hi @ekeever1 we are able to reproduce your issue internally and is currently in the process of investigation. Thanks!

**Comment by tcgu-amd** [comment]
Hi @ekeever, would you be able to try again to see if the issue is fixed now? Thanks!

**Comment by ekeever1** [comment]
Hi @tcgu-amd, I installed 6.2.4 yesterday without checksum issues. Thanks!
